#!/usr/bin/env php
<?php

if (!in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

set_time_limit(0);

require_once ("vendor/autoload.php");

$master = new \Thunderbug\QuakeConnection\Master\Master("cod4master.activision.com", 20810);
$servers = $master->getServerList();
foreach ($servers as $server) {
    $start = microtime(true);
    $gameserver = new \Thunderbug\QuakeConnection\Server\Gameserver($server->getIp(), $server->getPort());
    $gameserver->getStatus();

    $time = microtime(true) - $start;

    print($server->getIp().":".$server->getPort()." ".$time."\n");
    // +- 300 ms of processing time for each server
}